import { Inter, Roboto_Mono } from 'next/font/google'
import "./globals.css";
import TopNav from '@/components/TopNav';
import Footer from '@/components/Footer';
import SessionWrapper from '@/components/SessionWrapper';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blogs on New Technology",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
    <html lang="en">
      <body className={`${inter.className} prose-invert prose  max-w-none bg-[#0d1117] img:prose`}>
        <TopNav/>
        {children}
        <Footer/>
        </body>
    </html>
  </SessionWrapper>
  );
}
